# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Stat 159
tagline:          'UCB - Stat 159'
description:      'Reproducible and Collaborative Statistical Data Science.'
url:              http://gastonsanchez.com/stat159
baseurl:          http://gastonsanchez.com/stat159

author:
  name:           'Gaston Sanchez'
  url:            http://gastonsanchez.com

paginate:         5

# Custom vars
version:          Fall 2016

github:
  repo:           https://github.com/gastonstat/stat159
